
package app;

import DB.DBConnection;
//import com.teknikindustries.bulksms.SMS;
import java.awt.Color;
import java.util.concurrent.ThreadLocalRandom;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JSeparator;


public class Pin extends javax.swing.JFrame {

    /**
     * Creates new form Pin
     */
    public Pin() {
        
        initComponents();
       setLocation(200,75);
       setTitle("Pin code");
       
       jLabel20.setVisible(false); jLabel21.setVisible(false);
    }String name;String acno;int j;
public Pin(String cname,String ac,int i) {
        
        initComponents();
        
       setLocation(200,75);
       name=cname;
       acno=ac;
       j=i;
       jLabel21.setVisible(false);
       jLabel20.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(850, 580));
        setMinimumSize(new java.awt.Dimension(850, 580));

        jPanel1.setMaximumSize(new java.awt.Dimension(810, 560));
        jPanel1.setMinimumSize(new java.awt.Dimension(810, 560));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("My Metro ATM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ATM_100px.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setText("ENTER YOUR PIN-CODE");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jPasswordField1.setText("****");
        jPasswordField1.setBorder(null);
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 70, 130, 50));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 360, 13));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel4.setText("  1");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel4MouseReleased(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 60, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel5.setText("  2");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 60, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel6.setText("  3");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 60, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel7.setText("  4");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 60, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel8.setText("  5");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 60, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel9.setText("  6");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 60, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel10.setText("  7");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 60, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel11.setText("  8");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 60, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel12.setText("  9");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 60, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel13.setText("  0");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 60, -1));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel20.setText("Welcome");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 170, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 360, 450));

        jPanel3.setOpaque(false);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("CLEAR");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, -1, 50));

        jPanel4.setOpaque(false);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("CONFIRM");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, 130, 50));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel16.setText("\"Security Is Our");

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel17.setText("First Priority...\"");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(7, 7, 7)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 360, 50));
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/1752381 - Copy.jpg"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
jPasswordField1.setText(""); 
jLabel21.setText(name);
jLabel3.setVisible(false);
jLabel20.setVisible(true);
jLabel21.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255,255,255),1,true));
        jPanel2.setBackground(Color.black);
jPasswordField1.setBackground(Color.black);
jSeparator1.setBackground(Color.white);
jPasswordField1.setForeground(Color.white);
jLabel3.setForeground(Color.white);
jLabel4.setForeground(Color.white);
jLabel5.setForeground(Color.white);
jLabel6.setForeground(Color.white);
jLabel7.setForeground(Color.white);
jLabel8.setForeground(Color.white);
jLabel9.setForeground(Color.white);
jLabel10.setForeground(Color.white);
jLabel11.setForeground(Color.white);
jLabel12.setForeground(Color.white);
jLabel13.setForeground(Color.white);
jLabel21.setForeground(Color.white);
jLabel20.setForeground(Color.white);


// TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255,255,255),1,true));
        jPanel2.setBackground(Color.black);
jPasswordField1.setBackground(Color.black);
jSeparator1.setBackground(Color.white);
jPasswordField1.setForeground(Color.white);
jLabel3.setForeground(Color.white);
jLabel4.setForeground(Color.white);
jLabel5.setForeground(Color.white);
jLabel6.setForeground(Color.white);
jLabel7.setForeground(Color.white);
jLabel8.setForeground(Color.white);
jLabel9.setForeground(Color.white);
jLabel10.setForeground(Color.white);
jLabel11.setForeground(Color.white);
jLabel12.setForeground(Color.white);
jLabel13.setForeground(Color.white);
jLabel21.setForeground(Color.white);
jLabel20.setForeground(Color.white);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255,255,255),1,true));
        jPanel2.setBackground(Color.black);
jPasswordField1.setBackground(Color.black);
jSeparator1.setBackground(Color.white);
jPasswordField1.setForeground(Color.white);
jLabel3.setForeground(Color.white);
jLabel4.setForeground(Color.white);
jLabel5.setForeground(Color.white);
jLabel6.setForeground(Color.white);
jLabel7.setForeground(Color.white);
jLabel8.setForeground(Color.white);
jLabel9.setForeground(Color.white);
jLabel10.setForeground(Color.white);
jLabel11.setForeground(Color.white);
jLabel12.setForeground(Color.white);
jLabel13.setForeground(Color.white);
jLabel21.setForeground(Color.white);
jLabel20.setForeground(Color.white);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255,255,255),1,true));
        jPanel2.setBackground(Color.black);
jPasswordField1.setBackground(Color.black);
jSeparator1.setBackground(Color.white);
jPasswordField1.setForeground(Color.white);
jLabel3.setForeground(Color.white);
jLabel4.setForeground(Color.white);
jLabel5.setForeground(Color.white);
jLabel6.setForeground(Color.white);
jLabel7.setForeground(Color.white);
jLabel8.setForeground(Color.white);
jLabel9.setForeground(Color.white);
jLabel10.setForeground(Color.white);
jLabel11.setForeground(Color.white);
jLabel12.setForeground(Color.white);
jLabel13.setForeground(Color.white);
jLabel21.setForeground(Color.white);
jLabel20.setForeground(Color.white);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255,255,255),1,true));
        jPanel2.setBackground(Color.black);
jPasswordField1.setBackground(Color.black);
jSeparator1.setBackground(Color.white);
jPasswordField1.setForeground(Color.white);
jLabel3.setForeground(Color.white);
jLabel4.setForeground(Color.white);
jLabel5.setForeground(Color.white);
jLabel6.setForeground(Color.white);
jLabel7.setForeground(Color.white);
jLabel8.setForeground(Color.white);
jLabel9.setForeground(Color.white);
jLabel10.setForeground(Color.white);
jLabel11.setForeground(Color.white);
jLabel12.setForeground(Color.white);
jLabel13.setForeground(Color.white);
jLabel21.setForeground(Color.white);
jLabel20.setForeground(Color.white);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255,255,255),1,true));
        jPanel2.setBackground(Color.black);
jPasswordField1.setBackground(Color.black);
jSeparator1.setBackground(Color.white);
jPasswordField1.setForeground(Color.white);
jLabel3.setForeground(Color.white);
jLabel4.setForeground(Color.white);
jLabel5.setForeground(Color.white);
jLabel6.setForeground(Color.white);
jLabel7.setForeground(Color.white);
jLabel8.setForeground(Color.white);
jLabel9.setForeground(Color.white);
jLabel10.setForeground(Color.white);
jLabel11.setForeground(Color.white);
jLabel12.setForeground(Color.white);
jLabel13.setForeground(Color.white);
jLabel21.setForeground(Color.white);
jLabel20.setForeground(Color.white);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255,255,255),1,true));
        jPanel2.setBackground(Color.black);
jPasswordField1.setBackground(Color.black);
jSeparator1.setBackground(Color.white);
jPasswordField1.setForeground(Color.white);
jLabel3.setForeground(Color.white);
jLabel4.setForeground(Color.white);
jLabel5.setForeground(Color.white);
jLabel6.setForeground(Color.white);
jLabel7.setForeground(Color.white);
jLabel8.setForeground(Color.white);
jLabel9.setForeground(Color.white);
jLabel10.setForeground(Color.white);
jLabel11.setForeground(Color.white);
jLabel12.setForeground(Color.white);
jLabel13.setForeground(Color.white);
jLabel21.setForeground(Color.white);
jLabel20.setForeground(Color.white);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255,255,255),1,true));
        jPanel2.setBackground(Color.black);
jPasswordField1.setBackground(Color.black);
jSeparator1.setBackground(Color.white);
jPasswordField1.setForeground(Color.white);
jLabel3.setForeground(Color.white);
jLabel4.setForeground(Color.white);
jLabel5.setForeground(Color.white);
jLabel6.setForeground(Color.white);
jLabel7.setForeground(Color.white);
jLabel8.setForeground(Color.white);
jLabel9.setForeground(Color.white);
jLabel10.setForeground(Color.white);
jLabel11.setForeground(Color.white);
jLabel12.setForeground(Color.white);
jLabel13.setForeground(Color.white);
jLabel21.setForeground(Color.white);
jLabel20.setForeground(Color.white);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255,255,255),1,true));
        jPanel2.setBackground(Color.black);
jPasswordField1.setBackground(Color.black);
jSeparator1.setBackground(Color.white);
jPasswordField1.setForeground(Color.white);
jLabel3.setForeground(Color.white);
jLabel4.setForeground(Color.white);
jLabel5.setForeground(Color.white);
jLabel6.setForeground(Color.white);
jLabel7.setForeground(Color.white);
jLabel8.setForeground(Color.white);
jLabel9.setForeground(Color.white);
jLabel10.setForeground(Color.white);
jLabel11.setForeground(Color.white);
jLabel12.setForeground(Color.white);
jLabel13.setForeground(Color.white);
jLabel21.setForeground(Color.white);
jLabel20.setForeground(Color.white);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255,255,255),1,true));
        jPanel2.setBackground(Color.black);
jPasswordField1.setBackground(Color.black);
jSeparator1.setBackground(Color.white);
jPasswordField1.setForeground(Color.white);
jLabel3.setForeground(Color.white);
jLabel4.setForeground(Color.white);
jLabel5.setForeground(Color.white);
jLabel6.setForeground(Color.white);
jLabel7.setForeground(Color.white);
jLabel8.setForeground(Color.white);
jLabel9.setForeground(Color.white);
jLabel10.setForeground(Color.white);
jLabel11.setForeground(Color.white);
jLabel12.setForeground(Color.white);
jLabel13.setForeground(Color.white);
jLabel21.setForeground(Color.white);
jLabel20.setForeground(Color.white);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
jLabel4.setBorder(null);
        jPanel2.setBackground(Color.white);
jPasswordField1.setBackground(Color.white);
jSeparator1.setBackground(Color.black);
jPasswordField1.setForeground(Color.black);
jLabel3.setForeground(Color.black);
jLabel4.setForeground(Color.black);
jLabel5.setForeground(Color.black);
jLabel6.setForeground(Color.black);
jLabel7.setForeground(Color.black);
jLabel8.setForeground(Color.black);
jLabel9.setForeground(Color.black);
jLabel10.setForeground(Color.black);
jLabel11.setForeground(Color.black);
jLabel12.setForeground(Color.black);
jLabel13.setForeground(Color.black);        // TODO add your handling code here:
jLabel21.setForeground(Color.black);
jLabel20.setForeground(Color.black);

    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
 String EnterNumber=jPasswordField1.getText()+"1";
        jPasswordField1.setText(EnterNumber);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseReleased
    }//GEN-LAST:event_jLabel4MouseReleased

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255,255,255), 1, true));        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255,255,255), 1, true));        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
jPanel3.setBorder(null);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseExited

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
jPanel4.setBorder(null);          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseExited

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
jLabel5.setBorder(null);
        jPanel2.setBackground(Color.white);
jPasswordField1.setBackground(Color.white);
jSeparator1.setBackground(Color.black);
jPasswordField1.setForeground(Color.black);
jLabel3.setForeground(Color.black);
jLabel4.setForeground(Color.black);
jLabel5.setForeground(Color.black);
jLabel6.setForeground(Color.black);
jLabel7.setForeground(Color.black);
jLabel8.setForeground(Color.black);
jLabel9.setForeground(Color.black);
jLabel10.setForeground(Color.black);
jLabel11.setForeground(Color.black);
jLabel12.setForeground(Color.black);
jLabel13.setForeground(Color.black);        // TODO add your handling code here:
jLabel21.setForeground(Color.black);
jLabel20.setForeground(Color.black);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
jLabel6.setBorder(null);
        jPanel2.setBackground(Color.white);
jPasswordField1.setBackground(Color.white);
jSeparator1.setBackground(Color.black);
jPasswordField1.setForeground(Color.black);
jLabel3.setForeground(Color.black);
jLabel4.setForeground(Color.black);
jLabel5.setForeground(Color.black);
jLabel6.setForeground(Color.black);
jLabel7.setForeground(Color.black);
jLabel8.setForeground(Color.black);
jLabel9.setForeground(Color.black);
jLabel10.setForeground(Color.black);
jLabel11.setForeground(Color.black);
jLabel12.setForeground(Color.black);
jLabel13.setForeground(Color.black);        // TODO add your handling code here:
jLabel21.setForeground(Color.black);
jLabel20.setForeground(Color.black);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
jLabel7.setBorder(null);jPanel2.setBackground(Color.white);
jPasswordField1.setBackground(Color.white);
jSeparator1.setBackground(Color.black);
jPasswordField1.setForeground(Color.black);
jLabel3.setForeground(Color.black);
jLabel4.setForeground(Color.black);
jLabel5.setForeground(Color.black);
jLabel6.setForeground(Color.black);
jLabel7.setForeground(Color.black);
jLabel8.setForeground(Color.black);
jLabel9.setForeground(Color.black);
jLabel10.setForeground(Color.black);
jLabel11.setForeground(Color.black);
jLabel12.setForeground(Color.black);
jLabel13.setForeground(Color.black);        // TODO add your handling code here:
jLabel21.setForeground(Color.black);
jLabel20.setForeground(Color.black);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited

        jLabel8.setBorder(null);jPanel2.setBackground(Color.white);
jPasswordField1.setBackground(Color.white);
jSeparator1.setBackground(Color.black);
jPasswordField1.setForeground(Color.black);
jLabel3.setForeground(Color.black);
jLabel4.setForeground(Color.black);
jLabel5.setForeground(Color.black);
jLabel6.setForeground(Color.black);
jLabel7.setForeground(Color.black);
jLabel8.setForeground(Color.black);
jLabel9.setForeground(Color.black);
jLabel10.setForeground(Color.black);
jLabel11.setForeground(Color.black);
jLabel12.setForeground(Color.black);
jLabel13.setForeground(Color.black);        // TODO add your handling code here:
jLabel21.setForeground(Color.black);
jLabel20.setForeground(Color.black);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
jLabel9.setBorder(null);
        jPanel2.setBackground(Color.white);
jPasswordField1.setBackground(Color.white);
jSeparator1.setBackground(Color.black);
jPasswordField1.setForeground(Color.black);
jLabel3.setForeground(Color.black);
jLabel4.setForeground(Color.black);
jLabel5.setForeground(Color.black);
jLabel6.setForeground(Color.black);
jLabel7.setForeground(Color.black);
jLabel8.setForeground(Color.black);
jLabel9.setForeground(Color.black);
jLabel10.setForeground(Color.black);
jLabel11.setForeground(Color.black);
jLabel12.setForeground(Color.black);
jLabel13.setForeground(Color.black);        // TODO add your handling code here:
jLabel21.setForeground(Color.black);
jLabel20.setForeground(Color.black);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
jLabel10.setBorder(null);
        jPanel2.setBackground(Color.white);
jPasswordField1.setBackground(Color.white);
jSeparator1.setBackground(Color.black);
jPasswordField1.setForeground(Color.black);
jLabel3.setForeground(Color.black);
jLabel4.setForeground(Color.black);
jLabel5.setForeground(Color.black);
jLabel6.setForeground(Color.black);
jLabel7.setForeground(Color.black);
jLabel8.setForeground(Color.black);
jLabel9.setForeground(Color.black);
jLabel10.setForeground(Color.black);
jLabel11.setForeground(Color.black);
jLabel12.setForeground(Color.black);
jLabel13.setForeground(Color.black);        // TODO add your handling code here:
jLabel21.setForeground(Color.black);
jLabel20.setForeground(Color.black);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
jLabel11.setBorder(null);
        jPanel2.setBackground(Color.white);
jPasswordField1.setBackground(Color.white);
jSeparator1.setBackground(Color.black);
jPasswordField1.setForeground(Color.black);
jLabel3.setForeground(Color.black);
jLabel4.setForeground(Color.black);
jLabel5.setForeground(Color.black);
jLabel6.setForeground(Color.black);
jLabel7.setForeground(Color.black);
jLabel8.setForeground(Color.black);
jLabel9.setForeground(Color.black);
jLabel10.setForeground(Color.black);
jLabel11.setForeground(Color.black);
jLabel12.setForeground(Color.black);
jLabel13.setForeground(Color.black);        // TODO add your handling code here:
jLabel21.setForeground(Color.black);
jLabel20.setForeground(Color.black);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
jLabel12.setBorder(null);
        jPanel2.setBackground(Color.white);
jPasswordField1.setBackground(Color.white);
jSeparator1.setBackground(Color.black);
jPasswordField1.setForeground(Color.black);
jLabel3.setForeground(Color.black);
jLabel4.setForeground(Color.black);
jLabel5.setForeground(Color.black);
jLabel6.setForeground(Color.black);
jLabel7.setForeground(Color.black);
jLabel8.setForeground(Color.black);
jLabel9.setForeground(Color.black);
jLabel10.setForeground(Color.black);
jLabel11.setForeground(Color.black);
jLabel12.setForeground(Color.black);
jLabel13.setForeground(Color.black);        // TODO add your handling code here:
jLabel21.setForeground(Color.black);
jLabel20.setForeground(Color.black);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
jLabel13.setBorder(null);
        jPanel2.setBackground(Color.white);
jPasswordField1.setBackground(Color.white);
jSeparator1.setBackground(Color.black);
jPasswordField1.setForeground(Color.black);
jLabel3.setForeground(Color.black);
jLabel4.setForeground(Color.black);
jLabel5.setForeground(Color.black);
jLabel6.setForeground(Color.black);
jLabel7.setForeground(Color.black);
jLabel8.setForeground(Color.black);
jLabel9.setForeground(Color.black);
jLabel10.setForeground(Color.black);
jLabel11.setForeground(Color.black);
jLabel12.setForeground(Color.black);
jLabel13.setForeground(Color.black);        // TODO add your handling code here:
jLabel21.setForeground(Color.black);
jLabel20.setForeground(Color.black);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
jPasswordField1.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
try
{
    String pin=jPasswordField1.getText();
DBConnection db=new DBConnection();
db.pstmt=db.con.prepareStatement("select passwd from open_account_table where ac_no=?");
db.pstmt.setString(1,acno);
db.rst=db.pstmt.executeQuery();
if(db.rst.next())
{
    String pin1=db.rst.getString(1);
    if(pin.equals(pin1))
    {
        if(j==1)
        {
         new Transfer(acno).setVisible(true);
         this.setVisible(false);
        }
        else{
        try
        {int randomNum = ThreadLocalRandom.current().nextInt(1000, 9998 + 1);
     String t=String.valueOf(randomNum);
//       SMS smstut=new SMS();
          DBConnection db1=new DBConnection();
     db1.pstmt=db1.con.prepareStatement("select phone from open_account_table where ac_no=?");
     db1.pstmt.setString(1,acno);
     db1.rst=db1.pstmt.executeQuery();
     if(db1.rst.next())
     {
         String p=db1.rst.getString(1);
 //   smstut.SendSMS("Deep23", "1234qwer", "You are using My Metro Atm. Your One time Password(OTP) is "+t, p, "https://bulksms.vsms.net/eapi/submission/send_sms/2/2.0");
        new OTP(acno,t).setVisible(true);
        this.setVisible(false);
    }}catch(Exception e)
    {
        
    }
        }
    }
else
{
    try{
     ImageIcon icon1=new ImageIcon("denied.png");
          JOptionPane.showMessageDialog(null,null,null,JOptionPane.WARNING_MESSAGE,icon1) ;
}
    catch(Exception e)
    {
        
    }
}
}
else
{
    try{
     ImageIcon icon1=new ImageIcon("denied.png");
          JOptionPane.showMessageDialog(null,null,null,JOptionPane.WARNING_MESSAGE,icon1) ;
}
    catch(Exception e)
    {
        
    }
}
}
catch(Exception e)
{
    e.printStackTrace();
}


    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
 String EnterNumber=jPasswordField1.getText()+"2";
        jPasswordField1.setText(EnterNumber);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
 String EnterNumber=jPasswordField1.getText()+"3";
        jPasswordField1.setText(EnterNumber);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
 String EnterNumber=jPasswordField1.getText()+"4";
        jPasswordField1.setText(EnterNumber);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
 String EnterNumber=jPasswordField1.getText()+"5";
        jPasswordField1.setText(EnterNumber);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
 String EnterNumber=jPasswordField1.getText()+"6";
        jPasswordField1.setText(EnterNumber);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
 String EnterNumber=jPasswordField1.getText()+"7";
        jPasswordField1.setText(EnterNumber);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
 String EnterNumber=jPasswordField1.getText()+"8";
        jPasswordField1.setText(EnterNumber);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
 String EnterNumber=jPasswordField1.getText()+"9";
        jPasswordField1.setText(EnterNumber);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
 String EnterNumber=jPasswordField1.getText()+"0";
        jPasswordField1.setText(EnterNumber);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
      jPasswordField1.setBackground(Color.black);
jSeparator1.setBackground(Color.white);
jPasswordField1.setForeground(Color.white);
jLabel3.setForeground(Color.white);
jLabel4.setForeground(Color.white);
jLabel5.setForeground(Color.white
);
jLabel6.setForeground(Color.white);
jLabel7.setForeground(Color.white);
jLabel8.setForeground(Color.white);
jLabel9.setForeground(Color.white);
jLabel10.setForeground(Color.white);
jLabel11.setForeground(Color.white);
jLabel12.setForeground(Color.white);
jLabel13.setForeground(Color.white);
jLabel21.setForeground(Color.white);
jLabel20.setForeground(Color.white);
jPanel2.setBackground(Color.black);
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
       jPasswordField1.setBackground(Color.white);
jSeparator1.setBackground(Color.black);
jPasswordField1.setForeground(Color.black);
jLabel3.setForeground(Color.black);
jLabel4.setForeground(Color.black);
jLabel5.setForeground(Color.black);
jLabel6.setForeground(Color.black);
jLabel7.setForeground(Color.black);
jLabel8.setForeground(Color.black);
jLabel9.setForeground(Color.black);
jLabel10.setForeground(Color.black);
jLabel11.setForeground(Color.black);
jLabel12.setForeground(Color.black);
jLabel13.setForeground(Color.black);        // TODO add your handling code here:
jLabel21.setForeground(Color.black);
jLabel20.setForeground(Color.black);
jPanel2.setBackground(Color.white);
    }//GEN-LAST:event_jPanel2MouseExited

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
